### ISSUE TITLE
can share model and command line args for benchmarking ACO?

### ISSUE THREAD

**Issue by oscarbg** [Snektron/Xenodon#1]
just found this project on ACO bench thread (https://github.com/daniel-schuermann/mesa/issues/36) and I would like to test with ACO on Vega..
I compiled but:
./xenodon render
doesn't run:
Error: Missing required positional argument 
@Snektron can you share model used for benchmarking and exact command line to test?
./xenodon sysinfo
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
System setup information
GPU 0:
name: 'AMD RADV/ACO VEGA10 (LLVM 8.0.0)'
type: DiscreteGpu
pci bus: 00000000:03:00.0

**Comment by Snektron** [comment]
Hello, sorry for not writing any explanation for using the program earlier, i will do that right away. I quickly tested the renderer with one of the volumes i used for the benchmark results in my thesis, which are generated from the dataset provided by [the TNG project](http://www.tng-project.org). I don't know if i'm allowed to redistribute that though, i have sent a question about that to the people involved. While the data is open to anyone to access, it can take quite some resources to process it to a volume of the right type (a quick glance at the resources my python script to do that used showed 160 GB of virtual memory, and the dataset itself is another 20-60 GB depending on the one used).

**Comment by Snektron** [comment]
Alright, i've updated and expanded the program's help option, and added a more detailed README. Including explanation of how to benchmark and generate volumes. That should help you get along, minus the volume of course.

**Comment by oscarbg** [comment]
many thanks.. will try soon..

**Comment by oscarbg** [comment]
I tested and it works with bunny sample.. closing it..
